services:
  db:
    image: mongo:8.2.5
    env_file: .env
    volumes: [mongo_data:/data/db]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: .env
    healthcheck:
      # test:
      #   [
      #     "CMD",
      #     "node",
      #     "-e",
      #     "fetch('http://localhost:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))",
      #   ]
      test:
        [
          "CMD",
          "/usr/local/bin/bun",
          "-e",
          "fetch('http://localhost:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports: ["127.0.0.1:3000:3000"]

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file: .env
    ports: ["127.0.0.1:8080:80"]

volumes:
  mongo_data:
    driver: local

networks:
  default:
    driver: bridge
