packages:
  - backend
  - frontend

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - esbuild
  - unrs-resolver
  - vue-demi
