name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        task: [lint, typecheck, format]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: .nvmrc
          cache: pnpm
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run checks
        run: pnpm -r --if-present ${{ matrix.task }}
